name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [17, 18, 19]
        java_distro: [temurin, zulu, corretto]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Mustache Specs
        run: |
          git submodule update --init --recursive
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java_distro }}
          java-version: ${{ matrix.java_version }}
          cache: 'maven'
      - name: Install
        run: mvn clean install -DskipTests --batch-mode --no-transfer-progress
        env:
          BUILD_PORT: 0
          BUILD_SECURE_PORT: 0
      - name: Build
        run: mvn clean package --batch-mode --no-transfer-progress
        env:
          BUILD_PORT: 0
          BUILD_SECURE_PORT: 0
